from collections import Counter

from sqlalchemy.orm import Session

from app.models.draw import Draw


class FrequencyAnalyzer:

    @staticmethod
    def calculate(db: Session):

        draws = db.query(Draw).all()

        counter = Counter()

        for draw in draws:

            numbers = [
                draw.n1,
                draw.n2,
                draw.n3,
                draw.n4,
                draw.n5,
                draw.n6,
                draw.bonus,
                draw.chance,
            ]

            # Ignore toutes les valeurs NULL
            numbers = [n for n in numbers if n is not None]

            counter.update(numbers)

        return dict(sorted(counter.items(), key=lambda item: item[0]))