"""Create users and draws tables

Revision ID: 5a1f0e9eab0c
Revises:
Create Date: 2026-08-05 16:16:48.111823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1f0e9eab0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=50), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('n1', sa.Integer(), nullable=False),
    sa.Column('n2', sa.Integer(), nullable=False),
    sa.Column('n3', sa.Integer(), nullable=False),
    sa.Column('n4', sa.Integer(), nullable=False),
    sa.Column('n5', sa.Integer(), nullable=False),
    sa.Column('n6', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('chance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draws', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draws_draw_date'), ['draw_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_draws_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('draws', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draws_id'))
        batch_op.drop_index(batch_op.f('ix_draws_draw_date'))

    op.drop_table('draws')
    # ### end Alembic commands ###
